---
kind: pipeline
type: docker
name: default

steps:
- name: build-server
  image: golang:1.13
  commands:
  - make build
  when:
    event: push

- name: publish-server-image
  image: plugins/gcr
  settings:
    registry: gcr.io
    repo: wheresthetrain-nyc/bot
    context: ./cmd/server
    dockerfile: cmd/server/Dockerfile
    tag: "${DRONE_COMMIT}"
    json_key:
      from_secret: google_credentials
    when:
      branch: [master]
      event: push

- name: deploy
  image: nytimes/drone-gae
  settings:
    action: deploy
    project: wheresthetrain-nyc
    dir: cmd/server
    app_file: app.yaml
    addl_args: '{ "--image-url": "gcr.io/wheresthetrain-nyc/bot:${DRONE_COMMIT}" }'
    version: "${DRONE_COMMIT}"
    vars: '{ "KEY": "$$MTA_KEY" }'
  environment:
    GAE_CREDENTIALS:
      from_secret: google_credentials
    MTA_KEY:
      from_secret: mta_key
    when:
      branch: [master]
      event: push
